# Generated by Django 4.1.1 on 2022-09-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='94eoEwHkIZJwQSo', max_length=20, unique=True),
        ),
    ]
