# Generated by Django 4.1.1 on 2022-09-22 15:31

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_image_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageenroled',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packageenroled',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='students.package'),
        ),
        migrations.AlterField(
            model_name='packageenroled',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=students.models.generate_student_id, editable=False, max_length=20, unique=True),
        ),
    ]
